config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :questions

end

app/models/question.rb
class Question < ActiveRecord::Base
  Question.delete_all
  Question.create!(:id => 1, :title => "Do you want to build the next Social Network for Cats?", :lover => "cat", :answer => nil)
  Question.create!(:id => 2, :title => "Do you think dogs should be allowed everywhere people are?", :lover => "cat", :answer => nil)
  Question.create!(:id => 3, :title => "Your middle name is \"Meow\"?", :lover => "cat", :answer => nil)
  Question.create!(:id => 4, :title => "Is Snoop Dog one of your favourite artists?", :lover => "cat", :answer => nil)
  Question.create!(:id => 5, :title => "Do you spend all day watching cat videos?", :lover => "cat", :answer => nil)
  Question.create!(:id => 6, :title => "Do you stop people in the street to pet their dogs?", :lover => "cat", :answer => nil)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def question_params
    params.require(:question).permit(:title, :lover, :answer)
  end

  def show
    @questions = Question.all
    @question = Question.find(params[:id])
  end

  def update
    @questions = Question.all
    if params[:answer] == nil then
      reset_questions
      redirect_to Question.find(params[:id])
    else
      save_answer
      redirect_to Question.find(new_question)
    end
  end

  def reset_questions
    @questions.each do |question|
      question.update(answer: nil)
    end
  end

  def new_question
    newquestion = rand(1..@questions.size)
    until Question.find(newquestion).answer == nil
      newquestion = rand(1..@questions.size)
    end
    newquestion
  end

  def save_answer
    @question = Question.find(params[:id])
    @question.update(answer: params[:answer])
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      @questions = Question.all
      newquestion = rand(1..6)
      until Question.find(newquestion).answer == nil
        newquestion = rand(1..6)
      end
      @question = Question.find(newquestion)
      @intro = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ligula nunc, pellentesque tempus nisi nec, ultrices varius leo. Aenean ultrices sem ligula, at fringilla mi tincidunt in. Vestibulum vestibulum lacus eget pretium lacinia. Aenean sed pulvinar elit. Pellentesque sollicitudin ligula sapien, ac eleifend eros congue malesuada. Nulla iaculis dolor non ipsum ultrices rutrum. Proin nec mauris in justo porttitor faucibus. Integer blandit nisi nec dolor aliquam, pellentesque viverra mauris suscipit. Ut quis condimentum nisl. Duis finibus tortor sed eros rhoncus, ut pharetra purus bibendum. Proin non interdum dolor."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_result.html.erb
<% if @questions.where(answer: true, lover: "cat").size == @questions.where(answer: true, lover: "dog").size  %>
<p>Congratulations.</p>
<p>YOU ARE A PLANT LOVER!</p>
<% elsif @questions.where(answer: true, lover: "cat").size > @questions.where(answer: true, lover: "dog").size  %>
<p>Congratulations.</p>
<p>YOU ARE A CAT LOVER!</p>
<% else %>
<p>Congratulations.</p>
<p>YOU ARE A DOG LOVER!</p>
<% end %>
<p class="button"><%= link_to "Start a new Quiz", question_path(@question, id: rand(1..6), :answer => nil), :method => :put %></p>

app/views/questions/_selection.html.erb
<p class="button"><%= link_to "YES", question_path(@question, :answer => true), :method => :put %></p>
<p class="button"><%= link_to "NO", question_path(@question, :answer => false), :method => :put %></p>

app/views/questions/show.html.erb
<% if  @questions.where(answer: true).size + @questions.where(answer: false).size <= 2 %>
  <p>
    <strong>Title:</strong>
    <%= @question.title %>
  </p>
  <%= render 'selection' %>
  <p class="button"><%= link_to "HOME", root_path %></p>
<% else %>
  <%= render 'result' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Personality Quiz</h1>
<p><%= @intro %></p>
<% if  @questions.where(answer: true).size + @questions.where(answer: false).size >= 1 %>
  <p class="button"><%= link_to "Continue your Quiz", question_path(@question)%></p>
<% end %>
<p class="button"><%= link_to "Start a new Quiz", question_path(@question, id: rand(1..6), :answer => nil), :method => :put %></p>